version: '3.8'
services:
  app:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
  db:
    image: postgres:14-alpine
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env